### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by indoorsNB** [MoHaDouBiTeam/gregtech6-chinese-translation#30]
- [x] S:gt.stone.limestone. 石灰岩
- [x] 大黄蜂（有一个得问greg啥意思）
- [x] 多出来那一堆奇葩panel
- [x] 单元式流体容器
- [x] spikes
- [x] 各种Slime
- [x] BAWLS
- [x] 保险箱，充能工作台，locker之类的玩意
- [x] 各种药水
- [x] Sanding Machine
- [x] Long Distance Pipeline
- [x] Vent
- [x] Sodium Nitrate
- [x] Petroleum Coke
- [x] Alexandrite
- [x] 饮料toolTips
- [x] S:gt.lang.sealable. 方块特性
- [x] 食物
- [x] S:gt.multitileentity.data.switch.tooltip 深入探索
- [x] S:gt.td. 各种特性汉化
- [x] S:gt.tileentity.extender.tooltip.
- [x]  S:itemGroup 重新确认并统一
- [x] space
- [x] Redstonia
- [x] Potassium Sulfite
- [x] Potassium Persulfate
- [x] Potassium Nitrate
- [x] Potassium Carbonate
- [x] Potassium Aluminate
- [x] moon
- [x] moon turf
- [x] Maxixe
- [x] mars
- [x] mars turf
- [x] Manganese Chloride
- [x] Magnesium Chloride 
- [x] Magnesium Carbonate
- [x] Lithium Chloride
- [x] Ferrous Chloride
- [x] Ferric Chloride
- [x] Ferberite
- [x] Calcium Chloride
- [x] TungstenTrioxide
- [x] TungsticAcid
- [x] Mud 矿物
- [x] 反物质试管治疗
- [x] 各种晶体 （gem）
- [x] Mars 矿物
- [x] moon 矿物
- [x] Space 矿物
- [x] Kreknorite
- [x] Meteorite
- [x] Frezarite
- [x] Frozen Iron
- [x] Red Meteor
- [x] 新增multitileentity
- [x] 梅->莓
- [x] 粗糙的xxx纤维->生xxxx丝
- [x] 花
- [x] Obsidian Steel
- [x] Titanium Iron
- [x] Umberstone
- [x] UraniumEnriched
- [x] Petrified Wood
- [x] Jade
- [x] Christmas!
- [x] QT Stuffs
- [x] Botania Quartzs
- [x] 2018!

**Comment by NH4HCr2O7** [comment]
石灰岩已完成

**Comment by NH4HCr2O7** [comment]
好好汉化的，你是认真的么

**Comment by indoorsNB** [comment]
稍微更新了一下

**Comment by NH4HCr2O7** [comment]
Spikes和Panel已完成

**Comment by JackyJnirvana** [comment]
To-do列表可以试试用projects来实现，挺好用的

**Comment by indoorsNB** [comment]
我太蠢了，不会用projects (之前projects写了点东西一个人都没动过）

**Comment by Tanimodori** [comment]
To-do list has moved to projects, please DO NOT add items on this issue.
